### ISSUE TITLE
Update Docs Probot

### ISSUE THREAD

**Issue by cobraz** [SwedbankPay/swedbank-pay-sdk-js#111]
Hello :wave:

Before this repository was moved from @bjerkio organization, we had [update-docs](https://probot.github.io/apps/update-docs/) installed. This is a small robot that makes sure contributors update `docs/` when making changes to the codebase. There are configurations for it already [here](https://github.com/SwedbankPay/swedbank-pay-sdk-js/blob/alpha/.github/config.yml).

What do people think?

**Comment by NullableInt** [comment]
It looks like a cute bot. I am positive to this suggestion!

**Comment by cobraz** [comment]
You can see an example here: https://github.com/SwedbankPay/swedbank-pay-sdk-js/pull/9

**Comment by asbjornu** [comment]
The bot should now have access to all repositories under the `SwedbankPay` organisation. 😃 👍
