### ISSUE TITLE
Development/development strategy

### ISSUE THREAD

**Issue by cobraz** [SwedbankPay/swedbank-pay-sdk-js#188]
We talked about changing how we develop and deploy, in short, these are the changes we talked about:

- `master` --> `main` (meant for stable releases)
- `alpha` --> `develop` (meant for development)

`develop` branch will have _canary releases_, meaning it will release a prerelease version with every merge that contains at least one commit message annotated according to Conventional Commit.

We have to remember to change the configuration of Semantic Release with this change, this file:

https://github.com/SwedbankPay/swedbank-pay-sdk-js/blob/fc5ab9421f9fe0b72beaec5932ac48994b438019/.releaserc.json#L30-L38

The `next` branch will be used in the future for _next mayor_ releases.

cc: @asbjornu @NullableInt

**Comment by NullableInt** [comment]
👍 We could keep the `next` branch for release candidates, if this is something we want.

**Comment by asbjornu** [comment]
We can also use `release/*` branches for releases, as in standard Git Flow.

**Comment by cobraz** [comment]
I agree with you @asbjornu. Better to have a spec to reference than something special.

So we'll end up with something like this then? 👇

```json
"branches": [ 
   "+([0-9])?(.{+([0-9]),x}).x", 
   "main", 
   "release/*", 
   { 
     "name": "develop", 
     "prerelease": true 
   } 
 ] 
```

Who wants to do it?

**Comment by asbjornu** [comment]
Having `release/*` being named `develop` looks very strange to me. But that may just be because I'm not familiar with the semantic release process.

**Comment by cobraz** [comment]
```json
"branches": [ 
   "+([0-9])?(.{+([0-9]),x}).x", 
   "main",
   "release/*",
   { 
     "name": "develop", 
     "prerelease": true 
   } 
 ]
```

**Comment by cobraz** [comment]
Actually, after looking at this a second time, I think we should keep `next`. I don't know how I thought `release/*` would work with the proposed config … 🙄

But, to further explain the configuration I proposed above. `main` will automatically release to `main channel` (e.g. v1.0.0, v1.0.1 etc.). `develop` would be `develop channel` (e.g. v1.0.0-develop.1, v1.0.0-develop.2). The `develop channel` would be marked with prerelease in Github and NPM. In other words, like canary releases.

Also, the `+([0-9])?(.{+([0-9]),x}).x` branch, would be used to maintain a version, such as `v1` or `v1.2`. Let's pretend that we have moved on to `v2`, but we'd like to maintain `v1`, we'll create a branch named `1.x.x`. Every push to `1.x.x` would release new versions on `v1`. However, none of this actually works the way that Git Flow works for `release/*`, since they are branches meant to prepare for a release.

Developers would create a pull request with `develop` as the base branch. Once we are ready to release something for `main channel`, we'll merge it with `main`. We could use `next` for release candidates (and add prerelease tag for that) as @NullableInt suggested?

#### Example
```json
{
	"branches": [ 
	   	"+([0-9])?(.{+([0-9]),x}).x", 
	   	"main", 
		{
			"name": "next",
			"prerelease": "rc"
		},
	   	{ 
	     	"name": "develop", 
	     	"prerelease": true 
	   	} 
	]

```

**PS:** To support `main` as default branch, we have to make sure we are using Semantic Release 17.x. See: https://github.com/semantic-release/semantic-release/issues/1581

I don't know how `release/*` should be mixed in here, since Semantic Release automatically does version bumping etc before it creates a tag. Thoughts?

**Comment by asbjornu** [comment]
In Git Flow `+([0-9])?(.{+([0-9]),x}).x` would be equivalent to `support/*` branches. From what I understand, we have no need for `release/*` branches. As long as we only do stable releases from tagged commits on `main` we can do all planned releases from the `main` branch and tag appropriately with a stable or pre-release tag as we see fit.

**Comment by cobraz** [comment]
I'll create a quick pull request with documentation, so we can review the changes there. 👍
