### ISSUE TITLE
Unintended v1.0.0 release

### ISSUE THREAD

**Issue by cobraz** [SwedbankPay/swedbank-pay-sdk-js#213]
This is due to the fact that I merged #194 with `main` (being our default branch). I should've pushed it to `develop` 😅

How do we fix it? @asbjornu can remove the version on NPM within 72 hours of its release (it was released on 23th of December 2020 at 21:37 CET. E.g. 47 hours ago.

We can go ahead and delete the tags and release here at Github as well. Or, we accept having released v1.0.0 with only card payments (changing the description of the release to include card payments etc.)

Thoughts?

**Comment by cobraz** [comment]
@asbjornu you can also just give me access on NPM (`cobraz`), so I can fix it :)

**Comment by NullableInt** [comment]
I believe what is done is done.
v1.0.0 having only card payments should be fine I think. We can update it to v2 when we add a new payment instrument, and v3 for the next and so forth?

**Comment by cobraz** [comment]
Normally I'd let the API stabilize before releasing v1.0.0. I agree we can keep it and just move on :) We only need to release minor series, if we don't make any changes.
